version: '3.8'

services:

  nginx:
    build:
      context: nginx
    image: mikaelmicheline/fcnginx
    container_name: fcnginx
    ports:
      - "8080:8080"
    networks:
      - minhaRede
    depends_on:
      - node

  node:
    build:
      context: node
    image: mikaelmicheline/fcnode
    container_name: fcnode
    entrypoint: wait-for fcmysql:3306 -t 20 -- /usr/local/bin/docker-entrypoint.sh 
    command: sh -c "npm i && node index.js"
    networks:
      - minhaRede
    volumes:
      - ./node:/usr/src/app
    tty: true    
    depends_on:
      - mysql   

  mysql:
    build: 
      context: mysql 
    image: mikaelmicheline/fcmysql      
    container_name: fcmysql
    restart: always
    tty: true
    volumes:
      - ./mysql/mysqlData:/var/lib/mysql
    networks:
      - minhaRede

networks:
  minhaRede:
    driver: bridge